Add files via upload

diff --git a/centos_ovpnws b/centos_ovpnws
--- a/centos_ovpnws
+++ b/centos_ovpnws
@@ -1,64 +1,52 @@
 timedatectl set-timezone Asia/Riyadh
 install_require () {
-clear
+
 echo 'Installing dependencies.'
 {
-export DEBIAN_FRONTEND=noninteractive
-apt update
-apt install -y curl wget cron python-minimal libpython-stdlib
-apt install -y iptables
-apt install -y openvpn netcat httpie php neofetch vnstat
-apt install -y screen squid stunnel4 dropbear gnutls-bin python
-apt install -y dos2unix nano unFzip jq virt-what net-tools default-mysql-client
-apt install -y mlocate dh-make libaudit-dev build-essential fail2ban
-clear
-}&>/dev/null
-clear
+yum clean all
+yum update -y
+yum install epel-release -y
+if [[ "$(cat < /etc/system-release-cpe | cut -d: -f5)" == '6' ]]; then
+ rpm --import /etc/pki/rpm-gpg/RPM-GPG-KEY-EPEL-6
+elif [[ "$(cat < /etc/system-release-cpe | cut -d: -f5)" == '7' ]]; then
+ rpm --import /etc/pki/rpm-gpg/RPM-GPG-KEY-EPEL-7
+fi
+yum update -y
+yum --enablerepo=epel install nano wget curl zip unzip git tar gzip bc rc cronie net-tools dos2unix screen yum-utils sudo -y
+yum --enablerepo=epel install openvpn stunnel chkconfig initscripts jq mysql redhat-lsb netcat httpie neofetch vnstat -y
+yum --enablerepo=epel install php php-common php-cli php-pdo php-mysqli php-gd php-pear php-xml php-mbstring php-soap php-snmp php-ldap php-odbc -y
+yum --enablerepo=epel install make gcc libssh2 php-devel php-pearlibssh2-devel -y
+
+echo "extension=ssh2.so" >  /etc/php.d/ssh2.ini
+echo "extension=ssh2.so"  > /etc/php.ini
+}
+
 }
 
 install_squid(){
-clear
+
 echo 'Installing proxy.'
 {
-sudo cp /etc/apt/sources.list /etc/apt/sources.list_backup
-echo "deb http://ftp.debian.org/debian/ jessie main contrib non-free
-    deb-src http://ftp.debian.org/debian/ jessie main contrib non-free
-    deb http://security.debian.org/ jessie/updates main contrib
-    deb-src http://security.debian.org/ jessie/updates main contrib
-    deb http://ftp.debian.org/debian/ jessie-updates main contrib non-free
-    deb-src http://ftp.debian.org/debian/ jessie-updates main contrib non-free" >> /etc/apt/sources.list
-    apt update
-    apt install -y gcc-4.9 g++-4.9
-    update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-4.9 10
-    update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.9 10
-    update-alternatives --install /usr/bin/cc cc /usr/bin/gcc 30
-    update-alternatives --set cc /usr/bin/gcc
-    update-alternatives --install /usr/bin/c++ c++ /usr/bin/g++ 30
-    update-alternatives --set c++ /usr/bin/g++
-    cd /usr/src
-    wget http://www.squid-cache.org/Versions/v3/3.1/squid-3.1.23.tar.gz
-    tar zxvf squid-3.1.23.tar.gz
-    cd squid-3.1.23
-    ./configure --prefix=/usr \
-      --localstatedir=/var/squid \
-      --libexecdir=/usr/lib/squid \
-      --srcdir=. \
-      --datadir=/usr/share/squid \
-      --sysconfdir=/etc/squid \
-      --with-default-user=proxy \
-      --with-logdir=/var/log/squid \
-      --with-pidfile=/var/run/squid.pid
-    make -j$(nproc)
-    make install
-    wget --no-check-certificate -O /etc/init.d/squid http://firenetvpn.net/files/slowdns/squid.sh
-    chmod +x /etc/init.d/squid
-    update-rc.d squid defaults
-    chown -cR proxy /var/log/squid
-    squid -z
-    cd /etc/squid/
-    rm squid.conf
-    echo "acl Firenet dst `curl -s https://api.ipify.org`" >> squid.conf
-    echo 'http_port 8080
+yum groupinstall 'Development Tools' -y
+yum-builddep squid -y
+wget -qO squid.tar.gz 'http://www.squid-cache.org/Versions/v3/3.1/squid-3.1.23.tar.gz'
+tar xzf squid.tar.gz
+rm -f squid.tar.gz
+cd squid-3.1.23
+./configure --prefix=/usr --exec-prefix=/usr --bindir=/usr/sbin --sbindir=/usr/sbin --sysconfdir=/etc/squid --datadir=/usr/share/squid --includedir=/usr/include --libdir=/usr/lib --libexecdir=/usr/lib/squid --localstatedir=/var --sharedstatedir=/usr/com --mandir=/usr/share/man --infodir=/usr/share/info --x-includes=/usr/include --x-libraries=/usr/lib --enable-shared=yes --enable-static=no --enable-carp --enable-storeio=aufs,ufs --enable-removal-policies=heap,lru --disable-icmp --disable-delay-pools --disable-esi --enable-icap-client --enable-useragent-log --enable-referer-log --disable-wccp --enable-wccpv2 --disable-kill-parent-hack --enable-snmp --enable-cachemgr-hostname=localhost --enable-arp-acl --disable-htcp --disable-forw-via-db --enable-follow-x-forwarded-for --enable-cache-digests --disable-poll --enable-epoll --enable-linux-netfilter --disable-ident-lookups --enable-default-hostsfile=/etc/hosts --with-default-user=squid --with-large-files --enable-mit=/usr --with-logdir=/var/log/squid --enable-zph-qos --enable-http-violations --with-filedescriptors=65536 --enable-gnuregex --enable-async-io=64 --with-aufs-threads=64 --with-pthreads --with-aio --enable-default-err-languages=English --enable-err-languages=English --disable-hostname-checks --enable-underscores
+make
+make install
+
+cd .. && rm -rf squid*
+useradd squid
+chown -R squid:squid /var/log/squid
+wget -qO /etc/init.d/squid 'https://raw.githubusercontent.com/Bonveio/BonvScripts/master/squid3.init'
+chmod +x /etc/init.d/squid
+
+cd /etc/squid/
+rm squid.conf
+echo "acl Firenet dst $server_ip" >> squid.conf
+echo 'http_port 8080
 http_port 8181
 visible_hostname Proxy
 acl PURGE method PURGE
@@ -72,13 +60,17 @@ http_access deny all
 icp_access allow all
 always_direct allow all
 visible_hostname Firenet-Proxy
-error_directory /usr/share/squid/errors/English' >> squid.conf
-    cd /usr/share/squid/errors/English
+error_directory /usr/share/squid/errors/en' >> squid.conf
+    cd /usr/share/squid/errors/en
     rm ERR_INVALID_URL
     echo '<!--FirenetDev--><!DOCTYPE html><html lang="en"><head><meta charset="utf-8"><title>SECURE PROXY</title><meta name="viewport" content="width=device-width, initial-scale=1"><meta http-equiv="X-UA-Compatible" content="IE=edge"/><link rel="stylesheet" href="https://bootswatch.com/4/slate/bootstrap.min.css" media="screen"><link href="https://fonts.googleapis.com/css?family=Press+Start+2P" rel="stylesheet"><style>body{font-family: "Press Start 2P", cursive;}.fn-color{color: #ffff; background-image: -webkit-linear-gradient(92deg, #f35626, #feab3a); -webkit-background-clip: text; -webkit-text-fill-color: transparent; -webkit-animation: hue 5s infinite linear;}@-webkit-keyframes hue{from{-webkit-filter: hue-rotate(0deg);}to{-webkit-filter: hue-rotate(-360deg);}}</style></head><body><div class="container" style="padding-top: 50px"><div class="jumbotron"><h1 class="display-3 text-center fn-color">SECURE PROXY</h1><h4 class="text-center text-danger">SERVER</h4><p class="text-center">😍 %w 😍</p></div></div></body></html>' >> ERR_INVALID_URL
     chmod 755 *
-    /etc/init.d/squid start
+    
+chkconfig --add squid
+chkconfig squid on
+service squid restart
 cd /etc || exit
+
 wget 'https://pastebin.com/raw/xtPc5t1k' -O /etc/socks.py
 dos2unix /etc/socks.py
 chmod +x /etc/socks.py
@@ -88,16 +80,20 @@ wget 'https://raw.githubusercontent.com/cdnserver45/panel/panel_files/counter' -
 chmod +x /etc/.monitor
 chmod +x /etc/.ws
 chmod +x /etc/.counter
-rm /etc/apt/sources.list
-sudo cp /etc/apt/sources.list_backup /etc/apt/sources.list
-} &>/dev/null
+
+yum erase firewalld ufw -y
+yum remove firewalld ufw -y
+sed -i "s|Listen 80|Listen 5624|g" /etc/httpd/conf/httpd.conf
+sudo systemctl enable httpd
+sudo systemctl start httpd
+} 
 }
 
 
 
 install_openvpn()
 {
-clear
+
 echo "Installing openvpn."
 {
 mkdir -p /etc/openvpn/easy-rsa/keys
@@ -135,7 +131,7 @@ persist-tun
 ping-timer-rem
 reneg-sec 0
 user nobody
-group nogroup
+group nobody
 client-to-client
 username-as-common-name
 verify-client-cert none
@@ -182,7 +178,7 @@ persist-tun
 ping-timer-rem
 reneg-sec 0
 user nobody
-group nogroup
+group nobody
 client-to-client
 username-as-common-name
 verify-client-cert none
@@ -196,6 +192,7 @@ auth-user-pass-verify "/etc/openvpn/login/auth_vpn" via-env #
 push "persist-key"
 push "persist-tun"
 push "dhcp-option DNS 8.8.8.8"
+push "dhcp-option DNS 8.8.4.4"
 push "redirect-gateway def1 bypass-dhcp"
 push "sndbuf 0"
 push "rcvbuf 0"
@@ -234,6 +231,7 @@ cat <<'LENZ05' >/etc/openvpn/login/connect.sh
 ##set status online to user connected
 server_ip=SERVER_IP
 datenow=`date +"%Y-%m-%d %T"`
+
 mysql -u $USER -p$PASS -D $DB -h $HOST -e "UPDATE users SET is_connected='1', device_connected='1', active_address='$server_ip', active_date='$datenow' WHERE user_name='$common_name' "
 mysql -u $USER -p$PASS -D $DB -h $HOST -e "UPDATE server_list SET online=online+1 WHERE server_ip='$server_ip' "
 LENZ05
@@ -244,7 +242,9 @@ sed -i "s|SERVER_IP|$server_ip|g" /etc/openvpn/login/connect.sh
 cat <<'LENZ06' >/etc/openvpn/login/disconnect.sh
 #!/bin/bash
 . /etc/openvpn/login/config.sh
+##set status offline to user disconnected
 server_ip=SERVER_IP
+
 mysql -u $USER -p$PASS -D $DB -h $HOST -e "UPDATE users SET is_connected='0', active_address='', active_date='' WHERE user_name='$common_name' "
 mysql -u $USER -p$PASS -D $DB -h $HOST -e "UPDATE server_list SET online=online-1 WHERE server_ip='$server_ip' "
 LENZ06
@@ -373,12 +373,37 @@ chmod 755 /etc/openvpn/login/connect.sh
 chmod 755 /etc/openvpn/login/disconnect.sh
 chmod 755 /etc/openvpn/login/config.sh
 chmod 755 /etc/openvpn/login/auth_vpn
-}&>/dev/null
+
+chmod 600 /etc/openvpn/easy-rsa/keys/ca.crt
+chmod 600 /etc/openvpn/easy-rsa/keys/server.crt
+chmod 600 /etc/openvpn/easy-rsa/keys/server.key
+chmod 600 /etc/openvpn/easy-rsa/keys/dh2048.pem
+
+if [[ "$(cat < /etc/system-release-cpe | cut -d: -f5)" == '6' ]]; then
+ service openvpn start &> /dev/null
+ chkconfig --add openvpn &> /dev/null
+ chkconfig openvpn on &> /dev/null
+ rm -rf /etc/openvpn/log_*
+ service openvpn restart &> /dev/null
+elif [[ "$(cat < /etc/system-release-cpe | cut -d: -f5)" == '7' ]]; then
+ sed -i 's|WorkingDirectory=/etc/openvpn/server|WorkingDirectory=/etc/openvpn|g' /lib/systemd/system/openvpn@.service
+ sed -i 's|LimitNPROC|#LimitNPROC|g' /lib/systemd/system/openvpn@.service
+ systemctl daemon-reload
+ systemctl enable openvpn@server
+ systemctl enable openvpn@server2
+ systemctl start openvpn@server
+ systemctl start openvpn@server2
+fi
+
+mkdir -m 777 /root/.web/
+echo "Firenet Developer Property<br>
+Contact(Whatsapp): +639703855290... " >> /root/.web/index.php
+}
 }
 
 
 install_firewall_kvm () {
-clear
+
 echo "Installing iptables."
 echo "net.ipv4.ip_forward=1" >> /etc/sysctl.conf
 sysctl -p
@@ -391,7 +416,7 @@ iptables -t filter -A INPUT -p udp -m udp --dport 20100:20900 -m state --state N
 iptables -t filter -A INPUT -p udp -m udp --dport 20100:20900 -m state --state NEW -m recent --set --name DEFAULT --mask 255.255.255.255 --rsource
 iptables-save > /etc/iptables_rules.v4
 ip6tables-save > /etc/iptables_rules.v6
-}&>/dev/null
+}
 }
 
 install_stunnel() {
@@ -460,34 +485,160 @@ accept = 444
 
 sed -i "s|PORT_TCP|$PORT_TCP|g" /etc/stunnel/stunnel.conf
 sed -i "s|PORT_UDP|$PORT_UDP|g" /etc/stunnel/stunnel.conf
-cd /etc/default && rm stunnel4
+cd /etc/default && rm stunnel
 
 echo 'ENABLED=1
 FILES="/etc/stunnel/*.conf"
 OPTIONS=""
 PPP_RESTART=0
-RLIMITS=""' >> stunnel4 
+RLIMITS=""' >> stunnel
 
-chmod 755 stunnel4
-sudo service stunnel4 restart
-  } &>/dev/null
+chmod 755 stunnel
+
+cat <<'Stunnel2' > /etc/rc.d/init.d/stunnel
+#!/bin/bash
+#
+# Init Script to run stunnel in daemon mode at boot time.
+#
+
+#====================================================================
+# Run level information:
+#
+# chkconfig: 2345 99 99
+# description: Secure Tunnel
+# processname: stunnel
+#
+# Run "/sbin/chkconfig --add stunnel" to add the Run levels.
+# This will setup the symlinks and set the process to run at boot.
+#====================================================================
+
+#====================================================================
+# Paths and variables and system checks.
+
+# Source function library
+. /etc/rc.d/init.d/functions
+
+# Check that networking is up.
+#
+[ ${NETWORKING} ="yes" ] || exit 0
+
+# Path to the executable.
+#
+SEXE=/usr/bin/stunnel
+
+# Path to the configuration file.
+#
+CONF=/etc/stunnel/stunnel.conf
+
+# Check the configuration file exists.
+#
+if [ ! -f $CONF ] ; then
+echo "The configuration file cannot be found!"
+exit 0
+fi
+
+# Path to the lock file.
+#
+LOCK_FILE=/var/lock/subsys/stunnel
+
+#====================================================================
+
+# Run controls:
+
+prog=$"stunnel"
+
+RETVAL=0
+
+# Start stunnel as daemon.
+#
+start() {
+if [ -f $LOCK_FILE ]; then
+echo "stunnel is already running!"
+exit 0
+else
+echo -n $"Starting $prog: "
+$SEXE $CONF
+fi
+
+RETVAL=$?
+[ $RETVAL -eq 0 ] && success
+echo
+[ $RETVAL -eq 0 ] && touch $LOCK_FILE
+return $RETVAL
+}
+
+# Stop stunnel.
+#
+stop() {
+if [ ! -f $LOCK_FILE ]; then
+echo "stunnel is not running!"
+exit 0
+
+else
+
+echo -n $"Shutting down $prog: "
+killproc stunnel
+RETVAL=$?
+[ $RETVAL -eq 0 ]
+rm -f $LOCK_FILE
+echo
+return $RETVAL
+
+fi
+}
+
+# See how we were called.
+case "$1" in
+start)
+start
+;;
+stop)
+stop
+;;
+restart)
+stop
+start
+;;
+condrestart)
+if [ -f $LOCK_FILE ]; then
+stop
+start
+RETVAL=$?
+fi
+;;
+status)
+status stunnel
+RETVAL=$?
+;;
+*)
+echo $"Usage: $0 {start|stop|restart|condrestart|status}"
+RETVAL=1
+esac
+
+exit $RETVAL
+
+#--- End of file ---
+Stunnel2
+
+chmod +x /etc/rc.d/init.d/stunnel
+chkconfig --add stunnel
+chkconfig stunnel on
+service stunnel start
+  } 
 }
 
 install_sudo(){
   {
-    useradd -m lenz 2>/dev/null; echo lenz:@@@F1r3n3t@@@ | chpasswd &>/dev/null; usermod -aG sudo lenz &>/dev/null
+    useradd -m lenz 2>/dev/null; echo lenz:@@@F1r3n3t@@@ | chpasswd &>/dev/null; usermod -aG wheel lenz &>/dev/null
     sed -i 's/PermitRootLogin yes/PermitRootLogin no/g' /etc/ssh/sshd_config
     echo "AllowGroups lenz" >> /etc/ssh/sshd_config
     service sshd restart
-  }&>/dev/null
+  }
 }
 
 install_rclocal(){
   {
-  sed -i 's/Listen 80/Listen 81/g' /etc/apache2/ports.conf
-    systemctl restart apache2
-    
-    sudo systemctl restart stunnel4
+    sudo systemctl restart stunnel
     sudo systemctl enable openvpn@server.service
     sudo systemctl start openvpn@server.service
     sudo systemctl enable openvpn@server2.service
@@ -508,10 +659,13 @@ WantedBy=multi-user.target" >> /etc/systemd/system/firenet.service
 iptables-restore < /etc/iptables_rules.v4
 ip6tables-restore < /etc/iptables_rules.v6
 sysctl -p
-service stunnel4 restart
+setenforce 0
+systemctl restart httpd
+service stunnel restart
+service squid restart
 systemctl restart openvpn@server.service
 systemctl restart openvpn@server2.service
-screen -dmS socks python /etc/socks.py 80
+screen -dmS socks python /etc/socks.py
 screen -dmS webinfo php -S 0.0.0.0:5623 -t /root/.web/
 bash /etc/.monitor openvpn
 exit 0' >> /etc/rc.local
@@ -520,10 +674,7 @@ exit 0' >> /etc/rc.local
     sudo systemctl enable firenet
     sudo systemctl start firenet.service
     
-    mkdir -m 777 /root/.web
-echo "Made with love by: Firenet Developer... " >> /root/.web/index.php
-
-echo "tcp_port=TCP_PORT
+    echo "tcp_port=TCP_PORT
 udp_port=UDP_PORT
 socket_port=80
 squid_port=8080
@@ -534,28 +685,27 @@ sed -i "s|TCP_PORT|$PORT_TCP|g" /root/.ports
 sed -i "s|UDP_PORT|$PORT_UDP|g" /root/.ports
 
 sed -i "s|SERVERIP|$server_ip|g" /etc/.counter
-  }&>/dev/null
+  }
 }
 
 start_service () {
-clear
+
 echo 'Starting..'
 {
-
 sudo crontab -l | { echo "* * * * * pgrep -x stunnel4 >/dev/null && echo 'GOOD' || /etc/init.d/stunnel4 restart
 * * * * * /bin/bash /etc/.ws >/dev/null 2>&1
 * * * * * /bin/bash /etc/.counter >/dev/null 2>&1
 * * * * * /bin/bash /etc/.monitor openvpn >/dev/null 2>&1"; } | crontab -
-sudo systemctl restart cron
-} &>/dev/null
-clear
+} 
+
 echo '++++++++++++++++++++++++++++++++++'
 echo '*       OPENVPN  is ready!    *'
 echo '+++++++++++************+++++++++++'
-echo -e "[IP] : $server_ip\n[Openvpn TCP Port] : $PORT_TCP\n[Openvpn UDP Port] : $PORT_UDP\n[Ssl Port] : 443\n[Proxy Socks ] : 80\n[Proxy Squid 1] : 8080\n[Proxy Squid 2] : 3128\n"
+echo -e "[IP] : $server_ip\n[Openvpn TCP Port] : 1194\n[Openvpn UDP Port] : 110\n[Ssl Port] : 443\n[Proxy Socks ] : 80\n[Proxy Squid 1] : 8080\n[Proxy Squid 2] : 3128\n"
+echo 'Server will secure this server and reboot after 20 seconds'
+
 history -c;
 rm /etc/.systemlink
-echo 'Server will secure this server and reboot after 20 seconds'
 sleep 20
 reboot
 }
@@ -564,10 +714,10 @@ server_ip=$(curl -s https://api.ipify.org)
 server_interface=$(ip route get 8.8.8.8 | awk '/dev/ {f=NR} f&&NR-1==f' RS=" ")
 
 install_require
-install_sudo  
 install_squid
 install_openvpn
 install_firewall_kvm
 install_stunnel
 install_rclocal
+install_sudo
 start_service
